apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: soumyahe/apigateway:09af741602f2b3ed77e5d3d6234d522324071b5e
          ports:
            - containerPort: 3000
          env:
            - name: QUOTES_API
              value: "http://quotes-service:5000"
