apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: apigateway
          securityContext:
            allowPrivilegeEscalation: false
          image: soumyahe/apigateway:a85e76370b84e4717e9099251ce8fd946dbbfca7
          ports:
            - containerPort: 3000
          env:
            - name: QUOTES_API
              value: "http://quotes-service:5000"
