apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: apigateway
          securityContext:
            allowPrivilegeEscalation: false
          image: soumyahe/apigateway:d9c73b4f30eb48f9225489e71252b36abb73fc54
          ports:
            - containerPort: 3000
          env:
            - name: QUOTES_API
              value: "http://quotes-service:5000"
