apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: soumyahe/apigateway:15ea9057573c7bb06246ef322ef57f3d1b59e616
          ports:
            - containerPort: 3000
          env:
            - name: QUOTES_API
              value: "http://quotes-service:5000"
