apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quotes
  template:
    metadata:
      labels:
        app: quotes
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: quotes
          securityContext:
            allowPrivilegeEscalation: false
          image: soumyahe/quoteservice:a85e76370b84e4717e9099251ce8fd946dbbfca7
          ports:
            - containerPort: 5000
