apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quotes
  template:
    metadata:
      labels:
        app: quotes
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: quotes
          securityContext:
            allowPrivilegeEscalation: false
          image: soumyahe/quoteservice:59c42678cc28c12f2456bf6a18d4c8718ba3b13b
          ports:
            - containerPort: 5000
