name: DevSecOps Template

on: 
  workflow_call:
    inputs:
      service_path:
        description: 'Path to the service directory'
        required: true
        type: string
      servicetype:
        description: 'Type of the service (e.g., node, python, java)'
        required: true
        type: string
      secrets:
        SYNK_TOKEN:
          required: true
          type: string

jobs:
  security_scan: 
    name: Security Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.service_path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        # set up nodejs environment if the service type is node
      - name: Setup Environment
        if: ${{ inputs.servicetype == 'node' }}
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        
         # set up python environment if the service type is python
      - name: Setup Environment
        if: ${{ inputs.servicetype == 'python' }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
        # INSTALL DEPENDENCIES
      - name: Install dependencies
        run: |
          if [ "${{ inputs.servicetype }}" == "node" ]; then
            cd ${{ inputs.service_path }}
            npm install
          elif [ "${{ inputs.servicetype }}" == "python" ]; then
            cd ${{ inputs.service_path }}
            pip install -r requirements.txt

      
        # SCA - SNYK
      - name: Run Snyk scan (Node)
        if: inputs.service_type == 'node'
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: >
            --file=${{ inputs.service_path }}/package.json
            --severity-threshold=high
            --sarif-file-output=${{ inputs.service_path }}/snyk.sarif

      - name: Run Snyk scan (Python)
        if: inputs.service_type == 'python'
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: >
            --file=${{ inputs.service_path }}/requirements.txt
            --severity-threshold=high
            --sarif-file-output=${{ inputs.service_path }}/snyk.sarif
        
         # SAST - SEMGREP (ALL LANGUAGES)
      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep scan
        run: semgrep --config=auto --sarif --output=${{ inputs.service_path }}/semgrep.sarif

        # SECRET DETECTION -GITLEAKS (ALL LANGUAGES)
      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --report-format sarif --report-path=${{ inputs.service_path }}/gitleaks.sarif

      # UPLOAD RESULTS (SARIF)
      - name: Upload Snyk SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ inputs.service_path }}/snyk.sarif

      - name: Upload Semgrep SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ inputs.service_path }}/semgrep.sarif

      - name: Upload Bandit SARIF
        if: inputs.service_type == 'python'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ inputs.service_path }}/bandit.sarif

      - name: Upload Gitleaks SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif