name: API Gateway CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:

  security:
    uses: ./.github/workflows/code_security_template.yml
    with:
      service_path: ApiGateway
      service_type: node
    secrets: inherit

  container_security:
    uses: ./.github/workflows/container_security_template.yml
    with:
      service_path: ApiGateway
      service_type: node
    secrets: inherit

  dast:
    uses: ./.github/workflows/dast_security_template.yml
    with:
      image_name: soumyahe/apigateway:${{ github.run_number }}
      app_port: 3000
    secrets: inherit
