name: API Gateway CI

on:
  push:
    branches: [ main ]
    paths:
      - 'APIGateway/**'
      - '.github/workflows/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'APIGateway/**'
      - '.github/workflows/**'
permissions:
  contents: read
  security-events: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    with:
      service_path: APIGateway
      service_type: node
      image_name: soumyahe/apigateway
      app_port: 3000
      container_port: 3000
      health_path: /health
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  


    