name: API Gateway CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  security-events: write
jobs:
  security:
    uses: ./.github/workflows/devsecops-template.yml
    with:
      service_path: ApiGateway
      service_type: node
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}