name: CI Template
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

# =========================
# 1. REPO SECURITY
# =========================
  security_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Gitleaks Scan
        if: github.event_name == 'push'
        uses: gitleaks/gitleaks-action@v2

      - name: Semgrep SAST Scan
        if: github.event_name == 'push'
        uses: semgrep/semgrep-action@v1
        with:
          config: auto
          generateSarif: "1"

      - name: Upload Semgrep results
        if: always()  
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep.sarif
  code_security:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         include:
          - service: ApiGateway
            path: ApiGateway
            service_type: node

          - service: QuoteService
            path: QuoteService
            service_type: python

          - service: FrontendApplication
            path: FrontendApplication
            service_type: node

     steps:
      - uses: actions/checkout@v4

      
      - name: Setup Node
        if: matrix.service_type == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Python
        if: matrix.service_type == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd ${{ matrix.path }}
          if [ "${{ matrix.service_type }}" = "node" ]; then
            npm install
          else
            pip install -r requirements.txt
          fi


      - name: Run ESLint (Code Quality Check)
        run: |
           cd ${{ matrix.path }}
           if npm run | grep -q "lint"; then
              npm run lint
           else
              echo "No lint script found, skipping..."
           fi
      - name: Run Snyk Security Scan
        run: |
          cd ${{ matrix.path }}
          if [ "${{ matrix.service_type }}" = "node" ]; then
            npx snyk test --severity-threshold=critical
          else
           pip install pip-audit
           pip-audit -r requirements.txt
          fi
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Tests (if available)
        run: |
          cd ${{ matrix.path }}
          if [ "${{ matrix.service_type }}" = "node" ]; then
            if npm run | grep -q "test"; then
               npm test
            else
              echo "No tests found, skipping..."
            fi
          else
            if [ -d "tests" ]; then
               pip install pytest
               pytest tests/
            else
              echo "No tests found, skipping..."
            fi
          fi

