name: CI Template
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

# =========================
# 1. REPO SECURITY
# =========================
  security_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Gitleaks Scan
        if: github.event_name == 'push'
        uses: gitleaks/gitleaks-action@v2

      - name: Semgrep SAST Scan
        if: github.event_name == 'push'
        uses: semgrep/semgrep-action@v1
        with:
          config: auto
          generateSarif: "1"

      - name: Upload Semgrep results
        if: always()  
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep.sarif
  code_security:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         include:
          - service: ApiGateway
            path: ApiGateway
            service_type: node

          - service: QuoteService
            path: QuoteService
            service_type: python

          - service: FrontendApplication
            path: FrontendApplication
            service_type: node

     steps:
      - uses: actions/checkout@v4

      
      - name: Setup Node
        if: matrix.service_type == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Python
        if: matrix.service_type == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd ${{ matrix.path }}
          if [ "${{ matrix.service_type }}" = "node" ]; then
            npm install
          else
            pip install -r requirements.txt
          fi


      - name: Run ESLint (Code Quality Check)
        run: |
           cd ${{ matrix.path }}
           if npm run | grep -q "lint"; then
              npm run lint
           else
              echo "No lint script found, skipping..."
           fi
      - name: Run Snyk Security Scan
        run: |
          cd ${{ matrix.path }}
          if [ "${{ matrix.service_type }}" = "node" ]; then
            npx snyk test --severity-threshold=critical
          else
           pip install snyk
           snyk test --severity-threshold=critical
          fi
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Tests (if available)
        run: |
          cd ${{ matrix.path }}
          if [ "${{ matrix.service_type }}" = "node" ]; then
            if npm run | grep -q "test"; then
               npm test
            else
              echo "No tests found, skipping..."
            fi
          else
            if [ -d "tests" ]; then
               pip install pytest
               pytest tests/
            else
              echo "No tests found, skipping..."
            fi
          fi


# =========================
# 2. CONTAINER SECURITY
# =========================
  container_security:
    runs-on: ubuntu-latest
    needs: code_security

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.path }}
          file: ${{ matrix.path }}/app.dockerfile
          push: true
          tags: ${{ inputs.image_name }}:${{ github.sha }}

      - name: Scan Image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image_name }}:${{ github.sha }}
          format: sarif
          output: trivy.sarif

      - name: Smoke Test
        run: |
          docker run -d -p ${{ inputs.app_port }}:${{ inputs.container_port }} --name test \
          ${{ inputs.image_name }}:${{ github.sha }}

          sleep 10
          curl http://localhost:${{ inputs.app_port }}${{ inputs.health_path }}

# =========================
# 3. DAST
# =========================
  dast:
    runs-on: ubuntu-latest
    needs: container_security

    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker pull ${{ inputs.image_name }}:${{ github.sha }}

      - run: docker network create zap-net || true

      - name: Run App
        run: |
          docker run -d --name app --network zap-net \
          -p ${{ inputs.app_port }}:${{ inputs.container_port }} \
          ${{ inputs.image_name }}:${{ github.sha }}

      - name: Run ZAP
        run: |
          docker run --rm --network zap-net \
          ghcr.io/zaproxy/zaproxy:stable \
          zap-full-scan.py \
          -t http://app:${{ inputs.app_port }} \
          -m 5 -a || true
