name: Frontend Application CD

on:
  workflow_run:
    workflows: ["Frontend Application CI"]
    types:
      - completed

permissions:
  contents: write

jobs:
  cd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/cd.yaml
    with:
      service_name: frontendapplication
      image_name: soumyahe/frontendapplication
      deployment_file: k8s/frontendapplication-deployment.yaml

