name: Quote Service CI

on:
  push:
    branches: [ main ]
    paths:
      - 'QuoteService/**'
      - '.github/workflows/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'QuoteService/**'
      - '.github/workflows/**'


permissions:
  contents: read
  security-events: write


jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    with:
      service_path: QuoteService
      service_type: python
      image_name: soumyahe/quoteservice
      app_port: 5000
      container_port: 5000
      health_path: /
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


    