name: Quote Service CD

on:
  workflow_run:
    workflows: ["Quote Service CI"]
    types:
      - completed

permissions:
  contents: write

jobs:
  cd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/cd.yaml
    with:
      service_name: quoteservice
      image_name: soumyahe/quoteservice
      deployment_file: k8s/quoteservice-deployment.yaml

